### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by DamianReeves** [moonlight-coding/casper-nodejs#1]
How is this working out for you? Have you totally switched off of SpookyJS?

**Comment by pelallemant** [comment]
Sorry ! I didn't see the notification, didn't expect issues. I'll be more careful in the future !

I don't use SpookyJS since I wrote this library, SpookyJS doesn't allow 'then' calls once the scraping is started, it was the only reason i wrote this library.

The goal was to allow scraping in a dynamic context, an example is allowing to scrap ads list with pagination, another is to create bots for html5 games where there are data and buttons into tags.

I could invest time in order to make it decent to use (decent documentation, examples, unit tests and templates for general scraping cases).

**Comment by pelallemant** [comment]
To all those which thinks about using this library or spookyJS, there is far more complete: selenium-webdriver (for nodejs, for Java etc..) which does exactly the same thing as this library. I didn't know about that tool when i wrote casper-nodejs. I don't have the time to maintain this solution, please refer to selenium-webdriver, which in any case is far more complete.
